export const ALL_CATEGORIES = [
  { label: 'すべてのカテゴリ', keyword: '人気' },
  { label: 'レディースファッション', keyword: 'レディースファッション' },
  { label: 'メンズファッション', keyword: 'メンズファッション' },
  { label: 'インナー・下着・ナイトウェア', keyword: 'インナー 下着 ナイトウェア' },
  { label: 'バッグ・小物・ブランド雑貨', keyword: 'バッグ 小物 ブランド雑貨' },
  { label: '靴', keyword: '靴' },
  { label: '腕時計', keyword: '腕時計' },
  { label: 'ジュエリー・アクセサリー', keyword: 'ジュエリー アクセサリー' },
  { label: 'キッズ・ベビー・マタニティ', keyword: 'キッズ ベビー マタニティ' },
  { label: 'スポーツ・アウトドア', keyword: 'スポーツ アウトドア' },
  { label: 'ゴルフ', keyword: 'ゴルフ' },
  { label: '美容・コスメ・香水', keyword: '美容 コスメ 香水' },
  { label: 'ダイエット・健康', keyword: 'ダイエット 健康' },
  { label: '医薬品・コンタクト・介護', keyword: '医薬品 コンタクト 介護' },
  { label: '食品', keyword: '食品' },
  { label: 'スイーツ・お菓子', keyword: 'スイーツ お菓子' },
  { label: '水・ソフトドリンク', keyword: '水 ソフトドリンク' },
  { label: 'ビール・洋酒', keyword: 'ビール 洋酒' },
  { label: '日本酒・焼酎', keyword: '日本酒 焼酎' },
  { label: 'インテリア・寝具・収納', keyword: 'インテリア 寝具 収納' },
  { label: '日用品雑貨・文房具・手芸', keyword: '日用品雑貨 文房具 手芸' },
  { label: 'キッチン用品・食器・調理器具', keyword: 'キッチン用品 食器 調理器具' },
  { label: '家電', keyword: '家電' },
  { label: 'TV・オーディオ・カメラ', keyword: 'TV オーディオ カメラ' },
  { label: 'パソコン・周辺機器', keyword: 'パソコン 周辺機器' },
  { label: 'スマートフォン・タブレット', keyword: 'スマートフォン タブレット' },
  { label: '光回線・モバイル通信', keyword: '光回線 モバイル通信' },
  { label: 'おもちゃ', keyword: 'おもちゃ' },
  { label: 'ホビー', keyword: 'ホビー' },
  { label: '楽器・音響機器', keyword: '楽器 音響機器' },
  { label: '車用品・バイク用品', keyword: '車用品 バイク用品' },
  { label: '車・バイク', keyword: '車 バイク' },
  { label: 'CD・DVD', keyword: 'CD DVD' },
  { label: '本・雑誌・コミック', keyword: '本 雑誌 コミック' },
  { label: '電子書籍（楽天Kobo）', keyword: '電子書籍 楽天Kobo' },
  { label: 'ペットフード・ペット用品', keyword: 'ペットフード ペット用品' },
  { label: 'カタログギフト・チケット', keyword: 'カタログギフト チケット' }
];